blank_issues_enabled: true
contact_links:
  - name: 📖 Contributing guide
    url: https://github.com/moming2k/UK-IT/blob/main/CONTRIBUTING.md
    about: How to submit a new idea or join an existing project.
